version: '3.8'

services:
  backend:
    build: ./
    ports:
    - "8080:8080"
    - "5005:5005"
    environment:
      DB_IP: ${DB_IP}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: always
